language: cpp
compiler: gcc
sudo: false

os:
  - linux
  - osx

env:
  global:
    - SKIP_SASS_BINARY_DOWNLOAD_FOR_CI=true
  matrix:
    - export NODE_VERSION="6"

matrix:
  fast_finish: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.7
      - g++-4.7
      

before_install:
  - git submodule update --init --recursive
  - git clone https://github.com/creationix/nvm.git ./.nvm
  - source ./.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - npm config set python `which python`
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CC="gcc-4.7";
      export CXX="g++-4.7";
      export LINK="gcc-4.7";
      export LINKXX="g++-4.7";
      sudo apt install build-essential checkinstall libssl-dev;
    fi
  - gcc --version
  - g++ --version
  - rm package-lock.json
  - npm cache clean --f
  - rm -rf node_modules
  - npm install -g npm@latest-6

before_script:
  - npm install -g grunt-cli
  - npm install -g eslint

script:
  - npm install
  - npm test

cache:
  directories:
    - $HOME/.node-gyp
    - $HOME/.npm
